//////////////////////////////////////////////////////////////////////
function getOuterBuildings(aDoc,b,vType)
{
   var rx = $g("rx",aDoc);
   if ( rx ) 
   {
      //12 types of villages (only 6 if < T3.5)
      var dist = [
   /* 3-3-3-9 */[GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CROP,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 3-4-5-6 */[GID_IRON,GID_CROP,GID_LUMBER,GID_IRON,GID_CLAY,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 4-4-4-6 */[GID_LUMBER,GID_CROP,GID_LUMBER,GID_IRON,GID_CLAY,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 4-5-3-6 */[GID_LUMBER,GID_CROP,GID_LUMBER,GID_CLAY,GID_CLAY,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 5-3-4-6 */[GID_LUMBER,GID_CROP,GID_LUMBER,GID_IRON,GID_LUMBER,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 1-1-1-15*/[GID_CROP,GID_CROP,GID_LUMBER,GID_IRON,GID_CROP,GID_CROP,GID_CROP,GID_CROP,GID_CROP,GID_CROP,GID_CROP,GID_CROP,GID_CROP,GID_CROP,GID_CROP,GID_CLAY,GID_CROP,GID_CROP],
   /* 4-4-3-7 */[GID_LUMBER,GID_CROP,GID_CROP,GID_LUMBER,GID_CLAY,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 3-4-4-7 */[GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CLAY,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 4-3-4-7 */[GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_LUMBER,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 3-5-4-6 */[GID_IRON,GID_CROP,GID_LUMBER,GID_CLAY,GID_CLAY,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY],
   /* 4-3-5-6 */[GID_IRON,GID_LUMBER,GID_LUMBER,GID_IRON,GID_LUMBER,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CLAY,GID_CLAY,GID_IRON,GID_LUMBER,GID_CROP,GID_CROP,GID_CLAY,GID_CROP,GID_CROP],
   /* 5-4-3-6 */[GID_LUMBER,GID_CROP,GID_LUMBER,GID_LUMBER,GID_CLAY,GID_CLAY,GID_IRON,GID_CROP,GID_CROP,GID_IRON,GID_IRON,GID_CROP,GID_CROP,GID_LUMBER,GID_CROP,GID_CLAY,GID_LUMBER,GID_CLAY]
      ][vType - 1];

      var reRes = / +(\d+)/;
      var id, gid, crtLevel;

      for (var aNode = rx.firstChild; aNode; aNode = aNode.nextSibling)
      {
         if ( TAG(aNode) === "AREA" )
         {
            if ( reRes.exec(aNode.alt) )
            {
               crtLevel = parseInt10(RegExp.$1);
               id = parseInt10(parseUri(aNode.href).queryKey.id);
               if ( isFinite(id) )
               {
                  gid = dist[id - 1];
                  b[id] = [gid,crtLevel];
               }
            }
         }
      }
   }

   return b;
}
